In [1]:
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import atlite
import numpy as np
import logging 
logging.basicConfig(level=logging.INFO)
import xesmf as xe

/home/s233224/anaconda3/envs/atlite_cmip6_2025/lib/python3.13/site-packages/esmpy/interface/loadESMF.py:94: VersionWarning: ESMF installation version 8.8.0, ESMPy version 8.8.0b0
  warnings.warn("ESMF installation version {}, ESMPy version {}".format(


In [70]:
path = "/groups/EXTREMES/cutouts/"
files = [f'{path}europe-{year}-era5.nc' for year in range(1980, 1981)]
field="influx_direct"

# Open multiple ERA5 datasets
df = xr.open_mfdataset(files, combine="by_coords", join="inner")

In [53]:
df[field].mean(dim="time").size

29673

In [71]:
# Ensure time is sorted
df = df.sortby("time")

In [82]:
  # Resample and sum over each 3-hour period.
irradiance_3h_accumulated= df[field].resample(time="3H", label="left", closed="left").mean()



/home/s233224/anaconda3/envs/atlite_cmip6_2025/lib/python3.13/site-packages/xarray/groupers.py:487: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  self.index_grouper = pd.Grouper(


In [83]:
import pandas as pd
irradiance_3h_accumulated["time"] = irradiance_3h_accumulated["time"] + pd.Timedelta(hours=1.5)
irradiance_3h_accumulated

<xarray.DataArray 'influx_direct' (time: 2928, y: 157, x: 189)> Size: 348MB
dask.array<stack, shape=(2928, 157, 189), dtype=float32, chunksize=(1, 157, 189), chunktype=numpy.ndarray>
Coordinates:
  * x        (x) float64 2kB -12.0 -11.75 -11.5 -11.25 ... 34.25 34.5 34.75 35.0
  * y        (y) float64 1kB 33.0 33.25 33.5 33.75 ... 71.25 71.5 71.75 72.0
    lon      (x) float64 2kB dask.array<chunksize=(189,), meta=np.ndarray>
    lat      (y) float64 1kB dask.array<chunksize=(157,), meta=np.ndarray>
  * time     (time) datetime64[ns] 23kB 1980-01-01T01:30:00 ... 1980-12-31T22...
Attributes:
    units:    W m**-2
    module:   era5
    feature:  influx

In [84]:
irradiance_3h_accumulated.mean(dim="time").values

array([[151.02643 , 152.07144 , 152.95612 , ..., 161.98242 , 160.10077 ,
        158.39034 ],
       [149.58688 , 150.69011 , 151.76721 , ..., 160.97826 , 159.36981 ,
        158.36127 ],
       [148.22386 , 149.36227 , 150.43312 , ..., 160.6247  , 159.07303 ,
        158.04788 ],
       ...,
       [ 28.60058 ,  28.371069,  28.045532, ...,  33.120747,  33.05287 ,
         32.983135],
       [ 28.546053,  28.374958,  28.108969, ...,  31.65613 ,  31.611355,
         31.56472 ],
       [ 28.47118 ,  28.298325,  28.036179, ...,  30.29576 ,  30.261974,
         30.215965]], dtype=float32)

In [81]:
df['influx_direct'].mean(dim='time').values

array([[151.0262  , 152.07135 , 152.95622 , ..., 161.98233 , 160.10103 ,
        158.39017 ],
       [149.587   , 150.69016 , 151.7673  , ..., 160.97795 , 159.36995 ,
        158.36107 ],
       [148.22388 , 149.36238 , 150.43327 , ..., 160.62462 , 159.07315 ,
        158.04787 ],
       ...,
       [ 28.600624,  28.371143,  28.045563, ...,  33.12076 ,  33.05278 ,
         32.98311 ],
       [ 28.546124,  28.374996,  28.10903 , ...,  31.656143,  31.611378,
         31.564716],
       [ 28.471222,  28.298374,  28.036207, ...,  30.295715,  30.26199 ,
         30.215971]], dtype=float32)

In [85]:
fn="/groups/FutureWind/SFCRAD/MRI-ESM2-0/historical/r1i1p1f1/rsds_rsdsdiff_tas_1980.nc"
ds = xr.open_dataset(fn)
ds['rsds'].mean(dim='time').values

array([[240.26299 , 238.36028 , 237.73286 , ..., 274.47733 , 272.50058 ,
        271.4636  ],
       [234.55266 , 234.23973 , 232.16365 , ..., 272.3672  , 269.75723 ,
        267.68997 ],
       [230.63908 , 231.07448 , 228.67119 , ..., 268.73135 , 266.83542 ,
        264.0193  ],
       ...,
       [141.7456  , 139.51384 , 137.41753 , ...,  85.53884 ,  85.05604 ,
         84.48689 ],
       [138.57211 , 137.68442 , 134.78172 , ...,  83.67202 ,  83.896996,
         83.75063 ],
       [135.92198 , 135.4205  , 134.3191  , ...,  81.811295,  82.213875,
         82.56365 ]], dtype=float32)